[project]
name = "EyesCream"
version = "0.1.0"
dependencies = [
    "bs4>=0.0.2",
    "datetime>=5.5",
    "notion-client>=2.5.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "typing>=3.10.0.0",
]
